/*
 * gopro API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CameraStateResponse {
    #[serde(rename = "status")]
    pub status: Box<crate::models::CameraStateResponseStatus>,
}

impl CameraStateResponse {
    pub fn new(status: crate::models::CameraStateResponseStatus) -> CameraStateResponse {
        CameraStateResponse {
            status: Box::new(status),
        }
    }
}


