/*
 * gopro API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CameraStateResponseStatus {
    /// Is the system’s internal battery present?
    #[serde(rename = "1")]
    pub param_1: i32,
    /// Rough approximation of internal battery level in bars.
    #[serde(rename = "2")]
    pub param_2: i32,
    /// Is the system currently overheating?
    #[serde(rename = "6")]
    pub param_6: i32,
    /// Is the camera busy?
    #[serde(rename = "8")]
    pub param_8: i32,
    /// Is Quick Capture feature enabled?
    #[serde(rename = "9")]
    pub param_9: i32,
    /// Is the system encoding right now?
    #[serde(rename = "10")]
    pub param_10: i32,
    /// Is LCD lock active?
    #[serde(rename = "11")]
    pub param_11: i32,
    /// When encoding video, this is the duration (seconds) of the video so far; 0 otherwise.
    #[serde(rename = "13")]
    pub param_13: i32,
    /// Are Wireless Connections enabled?
    #[serde(rename = "17")]
    pub param_17: i32,
    /// The pairing state of the camera.
    #[serde(rename = "19")]
    pub param_19: i32,
    /// The last type of pairing that the camera was engaged in.
    #[serde(rename = "20")]
    pub param_20: i32,
    /// Time (milliseconds) since boot of last successful pairing complete action.
    #[serde(rename = "21")]
    pub param_21: i32,
    /// State of current scan for WiFi Access Points. Appears to only change for CAH-related scans.
    #[serde(rename = "22")]
    pub param_22: i32,
    /// The time, in milliseconds since boot that the WiFi Access Point scan completed.
    #[serde(rename = "23")]
    pub param_23: i32,
    /// WiFi AP provisioning state.
    #[serde(rename = "24")]
    pub param_24: i32,
    /// Wireless remote control version.
    #[serde(rename = "26")]
    pub param_26: i32,
    /// Is a wireless remote control connected?
    #[serde(rename = "27")]
    pub param_27: i32,
    /// Wireless Pairing State.
    #[serde(rename = "28")]
    pub param_28: i32,
    /// Provisioned WIFI AP SSID. On BLE connection, value is big-endian byte-encoded int.
    #[serde(rename = "29")]
    pub param_29: String,
    /// Camera’s WIFI SSID. On BLE connection, value is big-endian byte-encoded int.
    #[serde(rename = "30")]
    pub param_30: String,
    /// The number of wireless devices connected to the camera.
    #[serde(rename = "31")]
    pub param_31: i32,
    /// Is Preview Stream enabled?
    #[serde(rename = "32")]
    pub param_32: i32,
    /// Primary Storage Status.
    #[serde(rename = "33")]
    pub param_33: i32,
    /// How many photos can be taken before sdcard is full
    #[serde(rename = "34")]
    pub param_34: i32,
    /// How many minutes of video can be captured with current settings before sdcard is full
    #[serde(rename = "35")]
    pub param_35: i32,
    /// How many group photos can be taken with current settings before sdcard is full
    #[serde(rename = "36")]
    pub param_36: i32,
    /// Total number of group videos on sdcard
    #[serde(rename = "37")]
    pub param_37: i32,
    /// Total MB of space on the sdcard.
    #[serde(rename = "38")]
    pub param_38: i32,
    /// Number of photos on sdcard.
    #[serde(rename = "39")]
    pub param_39: i32,
    /// Number of videos on sdcard.
    #[serde(rename = "40", skip_serializing_if = "Option::is_none")]
    pub param_40: Option<i32>,
    /// OTA status.
    #[serde(rename = "41")]
    pub param_41: i32,
    /// Internal battery level (percent)
    #[serde(rename = "70")]
    pub param_70: i32,
}

impl CameraStateResponseStatus {
    pub fn new(param_1: i32, param_2: i32, param_6: i32, param_8: i32, param_9: i32, param_10: i32, param_11: i32, param_13: i32, param_17: i32, param_19: i32, param_20: i32, param_21: i32, param_22: i32, param_23: i32, param_24: i32, param_26: i32, param_27: i32, param_28: i32, param_29: String, param_30: String, param_31: i32, param_32: i32, param_33: i32, param_34: i32, param_35: i32, param_36: i32, param_37: i32, param_38: i32, param_39: i32, param_41: i32, param_70: i32) -> CameraStateResponseStatus {
        CameraStateResponseStatus {
            param_1,
            param_2,
            param_6,
            param_8,
            param_9,
            param_10,
            param_11,
            param_13,
            param_17,
            param_19,
            param_20,
            param_21,
            param_22,
            param_23,
            param_24,
            param_26,
            param_27,
            param_28,
            param_29,
            param_30,
            param_31,
            param_32,
            param_33,
            param_34,
            param_35,
            param_36,
            param_37,
            param_38,
            param_39,
            param_40: None,
            param_41,
            param_70,
        }
    }
}


