/*
 * gopro API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MediaDirectory {
    /// Directory name
    #[serde(rename = "d")]
    pub d: String,
    /// File system. Contains listing of media items in directory
    #[serde(rename = "fs")]
    pub fs: Vec<crate::models::MediaItem>,
}

impl MediaDirectory {
    pub fn new(d: String, fs: Vec<crate::models::MediaItem>) -> MediaDirectory {
        MediaDirectory {
            d,
            fs,
        }
    }
}


