/*
 * gopro API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct MediaResponse {
    /// Media list session identifier
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    /// Contains media info for for each directory (e.g. 100GOPRO/, 101GOPRO/, …)
    #[serde(rename = "media", skip_serializing_if = "Option::is_none")]
    pub media: Option<Vec<crate::models::MediaDirectory>>,
}

impl MediaResponse {
    pub fn new() -> MediaResponse {
        MediaResponse {
            id: None,
            media: None,
        }
    }
}


